apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "watchlist-frontend.fullname" . }}-env
data:
  env.js: |
    window._env_ = {
      REACT_APP_BACKEND_URL: "{{ .Values.runtimeEnv.REACT_APP_BACKEND_URL }}",
      REACT_APP_TMDB_API_KEY: "{{ .Values.runtimeEnv.REACT_APP_TMDB_API_KEY }}"
    };